# -*- coding: utf-8 -*-
"""ccai projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNbdj_DZEMf6-txCNTJBcBReT6c8xOxB
"""

import pandas as pd

print('MOVIE RECOMMENDATION SYSTEM')

my_movies = {
    'Movie_Name': ['GOAT', 'Leo', 'Jailer', 'Good Bad Ugly', 'Kanguva'],
    'Genre': ['Action', 'Action', 'Action', 'Action', 'Fantasy'],
    'Actor': ['Vijay', 'Vijay', 'Rajinikanth', 'Ajith', 'Suriya']
}
movie_df = pd.DataFrame(my_movies)

def get_recommendations(selected_genre):
    filtered_movies = movie_df[movie_df['Genre'] == selected_genre]
    return filtered_movies[['Movie_Name', 'Actor']]

my_choice = 'Action'
print("Recommended Movies:")
print(get_recommendations(my_choice))

import pandas as pd

print('STUDENT GRADE & PERFORMANCE PREDICTOR')
student_data = {
    'student_name': ['sri','aishu','vaishu','vasantha','reena'],
    'study_hours': [6,4,5,8,7],
    'test_score':[66,34,50,85,73]
}
df = pd.DataFrame(student_data)

def predict_performance(hours,score):
  if hours>=5 and score>=50:
    return 'pass'
  else:
    return 'fail'

new_student_hours = 8
new_student_score = 85

result = predict_performance(new_student_hours,new_student_score)

print('student performance report')
print('study hours:',new_student_hours)
print('test_score:',new_student_score)
print('therefore the prediction result :',result)

import pandas as pd

print('ECOMMERCE DISCOUNT CALCULATOR')

product_data = {
    'product_name': ['Laptop Bag', 'Wireless Mouse', 'Headphones', 'Keyboard'],
    'price': [1200, 450, 1500, 800]
}

df = pd.DataFrame(product_data)

def calculate_final_price(original_price):
    if original_price >= 1000:
        discount = original_price * 0.10
        final_price = original_price - discount
        return final_price, '10% Discount Applied'
    else:
        return original_price, 'No Discount'

item_price = 1200
final_bill, status = calculate_final_price(item_price)

print('\n--- Checkout Bill ---')
print('Original Price:', item_price)
print('Offer Status:', status)
print('Final Payable Amount:', final_bill)

import cv2
import numpy as np
import matplotlib.pyplot as plt

print('IMAGE PROCESSING - COLOR TO GRAYSCALE CONVERTER')

image = np.zeros((200, 200, 3), dtype=np.uint8)
image[30:170, 30:170] = [255, 100, 50]

def convert_to_grayscale(input_image):
    grayscale_image = cv2.cvtColor(input_image, cv2.COLOR_RGB2GRAY)
    return grayscale_image

gray_result = convert_to_grayscale(image)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))

axes[0].imshow(image)
axes[0].set_title('Original Color Image')

axes[1].imshow(gray_result, cmap='gray')
axes[1].set_title('Grayscale Image')

plt.show()

print('\nConversion Successful! Color image converted to Black & White.')

import pandas as pd

print('INSTAGRAM ALGORITHM - REEL VIRALITY PREDICTOR')

reels_data = {
    'reel_id': [1, 2, 3, 4],
    'likes': [15000, 200, 85000, 1200],
    'shares': [3000, 10, 12000, 50],
    'comments': [450, 5, 2100, 20]
}

df = pd.DataFrame(reels_data)

def predict_virality(likes, shares, comments):
    engagement_score = likes + (shares * 3) + (comments * 2)
    if engagement_score > 20000:
        return 'VIRAL REEL 🔥'
    elif engagement_score > 5000:
        return 'TRENDING REEL 🚀'
    else:
        return 'AVERAGE REEL 📉'

test_likes = 25000
test_shares = 4000
test_comments = 800

result = predict_virality(test_likes, test_shares, test_comments)

print('\n--- Instagram Analytics Report ---')
print('Likes:', test_likes)
print('Shares:', test_shares)
print('Comments:', test_comments)
print('Algorithm Result:', result)

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier

print('NLP MACHINE LEARNING - SENTIMENT ANALYZER (KNN)')

reviews = [
    'Great product very happy with purchase',
    'Excellent quality fast delivery loved it',
    'Worst product ever totally useless',
    'Bad quality waste of money terrible'
]
labels = ['Positive', 'Positive', 'Negative', 'Negative']

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(reviews)

model = KNeighborsClassifier(n_neighbors=1)
model.fit(X, labels)

test_review = ['Product was very good and excellent quality']
test_X = vectorizer.transform(test_review)

prediction = model.predict(test_X)

print('Test Input:', test_review[0])
print('ML Model Prediction:', prediction[0])

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

print('AI MEDICAL SCAN ANALYZER - HEART HOLE DETECTION')

X_scans = np.random.random((30, 64, 64, 1))
y_labels = np.random.randint(0, 2, size=(30, 1))

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_scans, y_labels, epochs=3, verbose=1)

def analyze_heart_scan(sample_scan):
    prediction = model.predict(sample_scan)
    if prediction[0][0] > 0.5:
        return 'HOLE DETECTED IN HEART WALL ⚠️'
    else:
        return 'NORMAL HEART STRUCTURE ❤️'

test_patient_scan = np.random.random((1, 64, 64, 1))
result = analyze_heart_scan(test_patient_scan)

print('\n--- Patient Heart Scan Analysis Report ---')
print('AI Prediction Outcome:', result)